### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by smnnlt** [nliulab/HRnV-Calc#3]
Please add guidelines for users on how to contribute to your software and how to seek help (see https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines). This may also include adding a code of conduct.

Issue during review for the JOSS (https://github.com/openjournals/joss-reviews/issues/5391)

**Comment by charlienew** [comment]
Thanks @smnnlt for your suggestion. We have added necessary guidelines in README about how others may be able to contribute to our software and how they could seek help on GitHub.
