### ISSUE TITLE
Treat file extensions as default postfix during patient id extraction

### ISSUE THREAD

**Issue by smnnlt** [nliulab/HRnV-Calc#5]
I don't think there is any case in which you want the file extension of the raw data file to be part of the new file names/extracted patient IDs. Thus I suggest to automatically remove the file extension for the patient id extraction, or in other words to add the file extension as the default postfix.

Issue during review for the JOSS (https://github.com/openjournals/joss-reviews/issues/5391).

**Comment by charlienew** [comment]
Thanks @smnnlt for your suggestion. We have updated the software to fix this issue in our latest release.
